68 multiple entries on go to definition
Viijay-Kr/react-ts-css pull request #70
Opened 2023-01-27 19:03 UTC by Viijay-Kr

Closes #68 

@karlhorky Here is the first draft to help avoid the extra definitions results from 

I m using a small [typescript plugin](https://www.npmjs.com/package/typescript-cleanup-definitions) to help this cause.

currently the option to override the definitions from declaration files can be done to settings Which is documented in the readme

Let me know what you think about this PR

2023-01-28 09:45 UTC, karlhorky commented on .vscode/launch.json
> +        "/Volumes/VijayK/private/rtcss-tsplugin/node_modules/typescript/bin/tsserver"
Should this path be hard coded?

2023-01-28 09:47 UTC, karlhorky commented on README.md
> +> Almost all the project scaffolders such as vite , next js and CRA adds css module declration  to the project by injecting it in '.d.ts' file (for instance inside `node_modules/vite/client.d.ts` add
```suggestion
> Almost all project scaffolders such as Vite, Next.js and CRA add css module declaration to the project by injecting it in a `.d.ts` file (for instance inside `node_modules/vite/client.d.ts` added by Vite). TypeScript treats these definitions as definition provider for Style properties. This results in a useless definition result when VS Code `Go to Definition` is triggered. Check this [issue](https://github.com/Viijay-Kr/react-ts-css/issues/68).
```

2023-01-28 09:49 UTC, karlhorky commented on README.md
> +> This extension gives you an option to avoid that  result  using a typescript plugin [typescript-cleanup-defs](https://www.npmjs.com/package/typescript-cleanup-definitions) that can filter out those
```suggestion
> This extension gives you an option to eliminate the useless results by using the TypeScript plugin [typescript-cleanup-defs](https://www.npmjs.com/package/typescript-cleanup-definitions) that can filter out those definitions results. Check the plugin for more details.
```

2023-01-28 09:50 UTC, karlhorky commented on examples/next-js-app-dir-css-modules/app/page.module.css
> +  },
Is this an error?

2023-01-28 09:53 UTC, karlhorky commented on package.json
> +            "node_modules/vite/client.d.ts",
Will these paths work at any level of the project?

Eg. In a monorepo / workspace project, the path would be:

```
<project root>/packages/package-name/node_modules/next/types/global.d.ts
```

Would be cool if these also worked out of the box without any additional configuration

2023-01-28 09:55 UTC, karlhorky requested changes
Seems like a really cool approach!

I suggested a few changes and asked some questions

2023-01-28 10:19 UTC, Viijay-Kr commented on .vscode/launch.json
> +        "/Volumes/VijayK/private/rtcss-tsplugin/node_modules/typescript/bin/tsserver"
This got in by mistake

2023-01-28 10:20 UTC, Viijay-Kr commented on package.json
> +            "node_modules/vite/client.d.ts",
it should since the plugin does a vague/naive string comparison .

2023-01-28 10:21 UTC, Viijay-Kr commented
> Seems like a really cool approach!
> 
> I suggested a few changes and asked some questions

Thanks a lot for the comments @karlhorky . Really Appreciate your time and effort.

2023-01-28 10:21 UTC, Viijay-Kr commented on examples/next-js-app-dir-css-modules/app/page.module.css
> +  },
yeah good catch

2023-01-28 17:02 UTC, Viijay-Kr commented on package.json
> +            "node_modules/vite/client.d.ts",
@karlhorky Added a mono repo setup in the latest commit to test this out . Tested both in vite and next app and tt works as I expected.

you can also test it . 
Open the monorepo folder in debug mode. Open `App.tsx` inside `examples/monorepo/packages/vite-app/src/App.tsx` and try going to the definition of `styles.logo`. You'll see only the css module definition is provided :)

2023-01-30 18:24 UTC, merged

2023-02-01 18:08 UTC, karlhorky commented
I tried this out just now in `v1.6.2`, but I'm still getting the duplicate entries:

<img width="1382" alt="Screenshot 2023-02-01 at 19 05 45" src="https://user-images.githubusercontent.com/1935696/216126254-9acf6fe3-7838-4d91-b76b-8293b149465e.png">


More details:

- Page: `packages/fusion.upleveled.io/app/(auth)/login/page.tsx`
- CSS Module File: `packages/fusion.upleveled.io/app/(auth)/login/page.module.scss`
- Next.js type definitions: `node_modules/next/types/global.d.ts`

2023-02-01 18:11 UTC, karlhorky commented
It seems like in [the `monorepo` example](https://github.com/Viijay-Kr/react-ts-css/tree/main/examples/monorepo), the `packages/next-app` workspace is not configured in `package.json`, wonder if this is related:

https://github.com/Viijay-Kr/react-ts-css/blob/19198f9c574550011a1df3e61ed2df3e04c91cfb/examples/monorepo/package.json#L5-L10

2023-02-01 18:17 UTC, karlhorky commented
If I should open a new issue, let me know.

2023-02-01 18:17 UTC, Viijay-Kr commented
@karlhorky I too tried it after the version was shipped . It did not work for me either. I suspect it could be something to do with the typescript version difference .

I did not have time to investigate this further.

Hope I will find some time to debug this.

2023-02-01 18:18 UTC, karlhorky commented
I'll create an issue so that we don't lose track of it.

2023-02-01 18:20 UTC, Viijay-Kr commented
> It seems like in [the `monorepo` example](https://github.com/Viijay-Kr/react-ts-css/tree/main/examples/monorepo), the `packages/next-app` workspace is not configured in `package.json`, wonder if this is related:
> 
> https://github.com/Viijay-Kr/react-ts-css/blob/19198f9c574550011a1df3e61ed2df3e04c91cfb/examples/monorepo/package.json#L5-L10
> 
> Eg. could that mean that the `node_modules/next/types/global.d.ts` is not being hoisted to the root?

This is not related . 

I have removed the next app from packages in order for the package to have it own node_modules folder . 

If you look at vite example it has its own node modules setup.So this helped to test the use case you mentioned

However removing the next app from the list of packages didn't make a difference since the monorepo was setup using turbo repo which provides a next boilerplate

2023-02-01 18:26 UTC, karlhorky commented
I reopened #68 and added a comment: https://github.com/Viijay-Kr/react-ts-css/issues/68#issuecomment-1412524350